import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { readMainModule } from "./helpers/main-source.mjs";

/**
 * The desktop spawns the agent sidecar by absolute path, and nothing used to
 * check that the path was one the bundler actually writes.
 *
 * `src/main/agent-sidecar.ts` pointed at `src/agent/runtime/dist/sidecar.js`
 * while `scripts/bundle-sidecar.mjs` emitted
 * `resources/runtime/sidecar.js`. `dist/` does not exist, so the
 * child died with MODULE_NOT_FOUND and the desktop booted with
 * HOST_UNAVAILABLE — but only from a source checkout, because the packaged path
 * (`<resources>/agent-runtime/sidecar.js`) was correct. Nothing failed in the
 * suite, so the breakage was invisible.
 *
 * These assertions compare the two modules' real paths rather than matching
 * either one against a literal, so a rename on either side is caught.
 */

const repoRoot = fileURLToPath(new URL("../", import.meta.url));
const sidecarSource = await readMainModule("agent-sidecar.ts");
const bundleScript = await readFile(
  new URL("../scripts/bundle-sidecar.mjs", import.meta.url),
  "utf8",
);
const desktopPackageJson = JSON.parse(
  await readFile(new URL("../package.json", import.meta.url), "utf8"),
);

/** Repo-relative segments of the bundler's output directory. */
function bundlerOutputDir() {
  const declaration = bundleScript.match(/const OUT_DIR = join\(ROOT,\s*([^)]+)\)/);
  assert.ok(declaration, "bundle-sidecar.mjs no longer declares OUT_DIR as join(ROOT, ...)");
  return [...declaration[1].matchAll(/"([^"]+)"/g)].map((match) => match[1]);
}

/**
 * Every `join(__dirname, "...")` candidate in agent-sidecar.ts.
 *
 * The array entry and the fallback return must agree: if they drift, a missing
 * bundle reports one location and is written to another.
 */
function sidecarCandidates() {
  const matches = [...sidecarSource.matchAll(/join\(__dirname,\s*"([^"]+)"\)/g)].map(
    (match) => match[1],
  );
  assert.ok(matches.length >= 2, "expected both a candidate and a fallback sidecar path");
  return matches;
}

test("the sidecar entry the desktop spawns is the file the bundler writes", () => {
  const expected = join(repoRoot, ...bundlerOutputDir(), "sidecar.js");
  // This module is bundled into out/main, so that is the __dirname the
  // candidate is relative to. `join` normalises the `../..` away, which is
  // exactly the resolution Electron performs at runtime.
  const resolved = sidecarCandidates().map((candidate) =>
    join(repoRoot, "out", "main", candidate),
  );

  for (const path of resolved) {
    assert.equal(
      path,
      expected,
      "agent-sidecar.ts must resolve to the sidecar.js that scripts/bundle-sidecar.mjs emits",
    );
  }
});

test("the sidecar candidate and its fallback agree", () => {
  const [first, ...rest] = sidecarCandidates();
  for (const candidate of rest) {
    assert.equal(
      candidate,
      first,
      "the fallback path must match the candidate, so a failed spawn names the real location",
    );
  }
});

test("the sidecar entry is not the unbundled dist path", () => {
  // The original defect: `dist/` is never produced by any script in this repo.
  assert.doesNotMatch(
    sidecarSource,
    /agent-runtime\/dist\/sidecar\.js/,
    "agent-runtime/dist/ is not produced by any build step; the bundle goes to resources/runtime/",
  );
});

test("the resolved sidecar entry exists once the bundle has been built", () => {
  const entry = join(repoRoot, ...bundlerOutputDir(), "sidecar.js");
  if (!existsSync(entry)) {
    // the bundle is generated by `npm run build:sidecar` and gitignored, so a
    // clean checkout legitimately has none. The path contract above still ran.
    return;
  }
  assert.ok(existsSync(entry), `${entry} must exist after build:sidecar`);
  // The ESM marker has to sit beside the entry or Node reads the bundle as
  // CommonJS and it dies on its first import.
  const manifest = join(repoRoot, ...bundlerOutputDir(), "package.json");
  assert.ok(existsSync(manifest), "package.json must ship beside sidecar.js");
});

test("the packaged sidecar path matches what electron-builder copies", () => {
  // The first candidate reads from `process.resourcesPath`, so its subpath must
  // be the extraResources `to` directory plus the bundler's file name.
  assert.match(
    sidecarSource,
    /join\(process\.resourcesPath \|\| "", "agent-runtime\/sidecar\.js"\)/,
    "the packaged candidate must be <resources>/agent-runtime/sidecar.js",
  );
  const entry = desktopPackageJson.build.extraResources.find(
    (resource) => resource.to === "agent-runtime",
  );
  assert.deepEqual(
    entry,
    { from: bundlerOutputDir().join("/"), to: "agent-runtime" },
  );
});
