export const PROTOCOL_VERSION = 11 as const;
export const SCHEMA_VERSION = 16 as const;
export const APP_ID = "net.dcode.app";
export const APP_NAME = "dcode";
export const APP_VERSION = "1.0.2";

export const APP_MENU_COMMANDS = [
  "newTask",
  "openProject",
  "openSettings",
  "openSearch",
  "openCommandPalette",
  "toggleSidebar",
  "openHelp",
  "openLogs",
  "checkForUpdates",
] as const;

export type AppMenuCommand = (typeof APP_MENU_COMMANDS)[number];

export const NATIVE_MENU_ACTIONS = [
  "undo",
  "redo",
  "cut",
  "copy",
  "paste",
  "selectAll",
  "reload",
  "zoomIn",
  "zoomOut",
  "resetZoom",
  "toggleFullScreen",
  "minimize",
  "toggleMaximize",
  "close",
  "restoreMainWindow",
  "toggleMainWindow",
] as const;

export type NativeMenuAction = (typeof NATIVE_MENU_ACTIONS)[number];

export const WINDOW_CONTROL_ACTIONS = [
  "getState",
  "minimize",
  "toggleMaximize",
  "close",
] as const;

export type WindowControlAction = (typeof WINDOW_CONTROL_ACTIONS)[number];

export const IPC = {
  invoke: {
    appGetVersion: "dcode/app/getVersion",
    appHealth: "dcode/app/health",
    appGetOnboarding: "dcode/app/getOnboarding",
    appDismissOnboarding: "dcode/app/dismissOnboarding",
    /** Installed system font families, resolved by Electron main. */
    systemFontsList: "dcode/app/systemFonts",
    updatesGetState: "dcode/updates/getState",
    updatesCheck: "dcode/updates/check",
    updatesDownload: "dcode/updates/download",
    updatesInstall: "dcode/updates/install",
    updatesOpenReleases: "dcode/updates/openReleases",
    notificationList: "dcode/notification/list",
    notificationMarkRead: "dcode/notification/markRead",
    notificationMarkAllRead: "dcode/notification/markAllRead",
    notificationClear: "dcode/notification/clear",
    notificationShowNative: "dcode/notification/showNative",
    notificationSetViewingSession: "dcode/notification/setViewingSession",
    agentPrompt: "dcode/agent/prompt",
    agentSteer: "dcode/agent/steer",
    promptEnhance: "dcode/prompt/enhance",
    speechTranscribe: "dcode/speech/transcribe",
    speechSynthesize: "dcode/speech/synthesize",
    speechGetStatus: "dcode/speech/getStatus",
    agentCompact: "dcode/agent/compact",
    agentAbort: "dcode/agent/abort",
    agentStop: "dcode/agent/stop",
    agentQueuePush: "dcode/agent/queue/push",
    agentQueueList: "dcode/agent/queue/list",
    agentQueueRemove: "dcode/agent/queue/remove",
    agentQueuePrioritize: "dcode/agent/queue/prioritize",
    agentQueueReorder: "dcode/agent/queue/reorder",
    agentGetStatus: "dcode/agent/getStatus",
    agentInstructionsGet: "dcode/agent/instructions/get",
    agentInstructionsSave: "dcode/agent/instructions/save",
    sessionList: "dcode/session/list",
    sessionCreate: "dcode/session/create",
    sessionFork: "dcode/session/fork",
    sessionMoveProject: "dcode/session/moveProject",
    sessionSearch: "dcode/session/search",
    sessionSearchContext: "dcode/session/searchContext",
    sessionGet: "dcode/session/get",
    sessionCollaboration: "dcode/session/collaboration",
    /** Validate and select a durable session from a reviewed host operation. */
    sessionOpen: "dcode/session/open",
    sessionDelete: "dcode/session/delete",
    sessionRename: "dcode/session/rename",
    sessionSummarizeTitle: "dcode/session/summarizeTitle",
    sessionConfigure: "dcode/session/configure",
    sessionImportScan: "dcode/session/importScan",
    sessionImportRun: "dcode/session/importRun",
    modelConfigImportScan: "dcode/modelConfig/importScan",
    modelConfigImportRun: "dcode/modelConfig/importRun",
    sessionReplaceMessages: "dcode/session/replaceMessages",
    sessionSaveRevision: "dcode/session/saveRevision",
    sessionListRevisions: "dcode/session/listRevisions",
    sessionActivateRevision: "dcode/session/activateRevision",
    sessionGetScratchPath: "dcode/session/getScratchPath",
    sessionOpenScratchPath: "dcode/session/openScratchPath",
    projectOpenFolder: "dcode/project/openFolder",
    settingsGet: "dcode/settings/get",
    settingsSet: "dcode/settings/set",
    networkProxyTest: "dcode/network/testProxy",
    commandShellList: "dcode/commandShell/list",
    secretsSet: "dcode/secrets/set",
    secretsDelete: "dcode/secrets/delete",
    secretsHas: "dcode/secrets/has",
    projectOpen: "dcode/project/open",
    projectPickFolders: "dcode/project/pickFolders",
    projectMemoryGet: "dcode/project/memory/get",
    projectMemorySave: "dcode/project/memory/save",
    projectGroupList: "dcode/project-group/list",
    projectGroupCreate: "dcode/project-group/create",
    projectGroupRename: "dcode/project-group/rename",
    projectGroupUpdate: "dcode/project-group/update",
    projectGroupMemoryGet: "dcode/project-group/memory/get",
    projectGroupMemorySave: "dcode/project-group/memory/save",
    projectGroupInstructionsGet: "dcode/project-group/instructions/get",
    projectGroupInstructionsSave: "dcode/project-group/instructions/save",
    projectClone: "dcode/project/clone",
    projectCloneCheckout: "dcode/project/cloneCheckout",
    projectGet: "dcode/project/get",
    projectList: "dcode/project/list",
    projectSet: "dcode/project/set",
    projectClear: "dcode/project/clear",
    projectRemove: "dcode/project/remove",
    pullsList: "dcode/pulls/list",
    scheduledList: "dcode/scheduled/list",
    scheduledCreate: "dcode/scheduled/create",
    scheduledUpdate: "dcode/scheduled/update",
    scheduledDelete: "dcode/scheduled/delete",
    scheduledRun: "dcode/scheduled/run",
    toolResolvePermission: "dcode/tool/resolvePermission",
    askToolResolve: "dcode/agent/askTool/resolve",
    plansPending: "dcode/plans/pending",
    plansResolve: "dcode/plans/resolve",
    /**
     * List every paired remote `pi-host` this desktop knows, redacted so no
     * device token reaches the renderer. See ADR 0286 (R2b pairing UX).
     */
    remoteHostList: "dcode/remoteHost/list",
    /**
     * Pair with a `pi-host` at `url` using a single-use `pairingToken`, mint
     * a device token, persist it encrypted, and open the live connection.
     */
    remoteHostPair: "dcode/remoteHost/pair",
    /** Close the live connection for `hostKey` and drop its persisted record. */
    remoteHostRemove: "dcode/remoteHost/remove",
    /**
     * Install and pair a `pi-host` on a machine the user reaches over SSH:
     * upload the bootstrap script, download and verify the published bundle
     * there, start the host, forward its loopback port, and exchange the
     * pairing token (spec §5.2). Uses the user's own SSH keys; no credential
     * crosses this channel.
     */
    remoteHostBootstrap: "dcode/remoteHost/bootstrap",
    remoteControlGetHostStatus: "dcode/remoteControl/getHostStatus",
    remoteControlSetHostEnabled: "dcode/remoteControl/setHostEnabled",
    remoteControlGeneratePairingToken: "dcode/remoteControl/generatePairingToken",
    providersList: "dcode/providers/list",
    providersReorder: "dcode/providers/reorder",
    providersCreate: "dcode/providers/create",
    providersUpdate: "dcode/providers/update",
    providersDelete: "dcode/providers/delete",
    /**
     * Set or clear one provider's API key. Separate from `providersUpdate`
     * because a plugin-declared row refuses a generic update while still
     * needing the credential its declaration asks for.
     */
    providersSetSecret: "dcode/providers/setSecret",
    providersTest: "dcode/providers/testConnection",
    providersListModels: "dcode/providers/listModels",
    providersRefreshModelCatalog: "dcode/providers/refreshModelCatalog",
    providersModelCatalogStatus: "dcode/providers/modelCatalogStatus",
    providersOauthVendors: "dcode/providers/oauth/vendors",
    providersOauthStart: "dcode/providers/oauth/start",
    providersOauthRespond: "dcode/providers/oauth/respond",
    providersOauthCancel: "dcode/providers/oauth/cancel",
    providersOauthDelete: "dcode/providers/oauth/delete",
    pluginList: "dcode/plugin/list",
    /** Plugin-contributed agent extensions (D387/D388, ADR 0214). */
    pluginImportExtension: "dcode/plugin/importExtension",
    extensionsCommandRun: "dcode/extensions/commands/run",
    extensionsUiRespond: "dcode/extensions/ui/respond",
    pluginLoadDev: "dcode/plugin/loadDev",
    /**
     * The answer to a development plugin's permission review. Loading a folder
     * is a two-step: `pluginLoadDev` returns the declaration, and this commits
     * the permissions the user accepted.
     */
    pluginLoadDevConfirm: "dcode/plugin/loadDevConfirm",
    pluginReload: "dcode/plugin/reload",
    /** Commits a reviewed widening for an already-loaded development plugin. */
    pluginReloadConfirm: "dcode/plugin/reloadConfirm",
    pluginCreateFromTemplate: "dcode/plugin/createFromTemplate",
    pluginInstallFromPath: "dcode/plugin/installFromPath",
    pluginInstallFromPackage: "dcode/plugin/installFromPackage",
    pluginEnable: "dcode/plugin/enable",
    pluginDisable: "dcode/plugin/disable",
    pluginSetScope: "dcode/plugin/setScope",
    pluginUninstall: "dcode/plugin/uninstall",
    pluginSettingsGet: "dcode/plugin/settings/get",
    pluginSettingsSet: "dcode/plugin/settings/set",
    pluginOpenPanel: "dcode/plugin/openPanel",
    pluginLauncherToggle: "dcode/pluginLauncher/toggle",
    pluginLauncherDismiss: "dcode/pluginLauncher/dismiss",
    pluginThemes: "dcode/plugin/themes",
    pluginScenicThemesDestinations: "dcode/plugin/scenicThemes/destinations",
    pluginScenicThemesSetBlur: "dcode/plugin/scenicThemes/setBlur",
    pluginServices: "dcode/plugin/services",
    pluginViews: "dcode/plugin/views",
    pluginViewOpen: "dcode/plugin/view/open",
    pluginViewClose: "dcode/plugin/view/close",
    pluginViewSetBounds: "dcode/plugin/view/setBounds",
    pluginViewSetVisible: "dcode/plugin/view/setVisible",
    mcpList: "dcode/mcp/list",
    mcpUpsert: "dcode/mcp/upsert",
    mcpRemove: "dcode/mcp/remove",
    mcpSetEnabled: "dcode/mcp/setEnabled",
    mcpSetScope: "dcode/mcp/setScope",
    mcpTransfer: "dcode/mcp/transfer",
    mcpTest: "dcode/mcp/test",
    mcpOauthStart: "dcode/mcp/oauth/start",
    mcpOauthCancel: "dcode/mcp/oauth/cancel",
    mcpImport: "dcode/mcp/import",
    mcpImportScan: "dcode/mcp/importScan",
    mcpImportRun: "dcode/mcp/importRun",
    skillList: "dcode/skill/list",
    skillCreate: "dcode/skill/create",
    skillImport: "dcode/skill/import",
    skillImportScan: "dcode/skill/importScan",
    skillImportRun: "dcode/skill/importRun",
    skillUpdate: "dcode/skill/update",
    skillRemove: "dcode/skill/remove",
    skillSetEnabled: "dcode/skill/setEnabled",
    skillSetScope: "dcode/skill/setScope",
    skillTransfer: "dcode/skill/transfer",
    skillRead: "dcode/skill/read",
    skillReveal: "dcode/skill/reveal",
    subagentList: "dcode/subagent/list",
    subagentCatalog: "dcode/subagent/catalog",
    subagentCreate: "dcode/subagent/create",
    subagentUpdate: "dcode/subagent/update",
    subagentRead: "dcode/subagent/read",
    subagentRemove: "dcode/subagent/remove",
    subagentSetEnabled: "dcode/subagent/setEnabled",
    subagentSetScope: "dcode/subagent/setScope",
    subagentSetBuiltinEnabled: "dcode/subagent/setBuiltinEnabled",
    subagentReveal: "dcode/subagent/reveal",
    commandPaletteSearch: "dcode/commandPalette/search",
    commandPaletteExecute: "dcode/commandPalette/execute",
    logOpenFolder: "dcode/log/openFolder",
    devtoolsToggle: "dcode/devtools/toggle",
    composerPickFiles: "dcode/composer/pickFiles",
    composerPickPhotos: "dcode/composer/pickPhotos",
    composerImportFiles: "dcode/composer/importFiles",
    composerPasteFiles: "dcode/composer/pasteFiles",
    clipboardRecordPaste: "dcode/clipboard/recordPaste",
    composerCommands: "dcode/composer/commands",
    workspaceDiff: "dcode/workspace/diff",
    workspaceReviewRollback: "dcode/workspace/review/rollback",
    browserNavigate: "dcode/browser/navigate",
    browserAction: "dcode/browser/action",
    browserSetBounds: "dcode/browser/setBounds",
    browserSetVisible: "dcode/browser/setVisible",
    browserOpenExternal: "dcode/browser/openExternal",
    browserGetState: "dcode/browser/getState",
    fsList: "dcode/fs/list",
    fsRead: "dcode/fs/read",
    fsReadImageDataUrl: "dcode/fs/readImageDataUrl",
    statsGetTokenUsageHistory: "dcode/stats/getTokenUsageHistory",
    fsReveal: "dcode/fs/reveal",
    fsOpen: "dcode/fs/open",
    fsIndex: "dcode/fs/index",
    fsResolveRef: "dcode/fs/resolveRef",
    windowSetWorkPanelReservation:
      "dcode/window/setWorkPanelReservation",
    windowSetWorkPanelChatWidth: "dcode/window/setWorkPanelChatWidth",
    windowSetBackgroundColor: "dcode/window/setBackgroundColor",
    windowControl: "dcode/window/control",
    closeBehaviorGet: "dcode/window/closeBehavior/get",
    closeBehaviorSet: "dcode/window/closeBehavior/set",
    menuRendererReady: "dcode/menu/rendererReady",
    traySetSessionPreferences: "dcode/tray/setSessionPreferences",
    nativeMenuAction: "dcode/menu/nativeAction",
  },
  event: {
    pluginChanged: "dcode/event/pluginChanged",
    /** Progress of an install or update, while it is still running. */
    pluginInstallProgress: "dcode/plugin/event/installProgress",
    /** Host-originated app settings mutation (e.g. plugin `app.setTheme`). */
    settingsChanged: "dcode/app/event/settingsChanged",
    extensionsUiPrompt: "dcode/extensions/event/uiPrompt",
    extensionsStatus: "dcode/extensions/event/status",
    pluginLauncherShown: "dcode/pluginLauncher/event/shown",
    agentMessage: "dcode/agent/event/message",
    agentQueueChanged: "dcode/agent/event/queueChanged",
    hostStatus: "dcode/app/event/hostStatus",
    toast: "dcode/app/event/toast",
    browserState: "dcode/browser/event/state",
    browserPreview: "dcode/browser/event/preview",
    windowMaximized: "dcode/window/event/maximized",
    windowFullScreen: "dcode/window/event/fullscreen",
    windowWorkPanelResize: "dcode/window/event/workPanelResize",
    menuCommand: "dcode/menu/event/command",
    traySessionActivated: "dcode/tray/event/sessionActivated",
    notificationChanged: "dcode/notification/event/changed",
    sessionsChanged: "dcode/session/event/changed",
    notificationActivated: "dcode/notification/event/activated",
    plansChanged: "dcode/plans/event/changed",
    providersOauth: "dcode/providers/oauth/event",
    mcpOauth: "dcode/mcp/oauth/event",
    updatesState: "dcode/updates/event/state",
  },
} as const;

export const IPC_WHITELIST = new Set<string>([
  ...Object.values(IPC.invoke),
  ...Object.values(IPC.event),
]);
